#ifndef TEST_FAILURE_CODES_H
#define TEST_FAILURE_CODES_H

#define T_SUCCESS 0
#define T_FAILURE_TEST_NOT_INITIALIZED -501
#define T_FAILURE_UNCAUGHT_STD_EXCEPTION -502
#define T_FAILURE_UNCAUGHT_NON_STD_EXCEPTION -503
#define T_FAILURE_TO_INITIALIZE_BLANK 3
#define T_FAILURE_TO_INITIALIZE_INIT_LIST 4

#define T_COPY_CONSTRUCT_MISMATCH 20
#define T_COPY_ASSIGNMENT_MISMATCH 21
#define T_MOVE_CONSTRUCT_MISMATCH 22
#define T_MOVE_ASSIGNMENT_MISMATCH 23

#endif 